<?php

namespace AppBundle\Repository;

/**
 * SutartisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SutartisRepository extends \Doctrine\ORM\EntityRepository
{
}
