<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * SutartisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SutartisRepository extends \Doctrine\ORM\EntityRepository {
    public function getDataByDate(User $user = null, \DateTime $dateStart, \DateTime $dateEnd){
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.inputDate >= :dateStart')
            ->andWhere('t.inputDate <= :dateEnd')
            ->andWhere('t.user = :user')
            ->setParameters([
                'dateStart' => $dateStart,
                'dateEnd' => $dateEnd,
                'user' => $user,
            ]);
        return $qb->getQuery()->getResult();
    }
}
